source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Eson_Example' do
  pod 'Eson', :path => '../'
end

target 'Eson_Tests' do
  pod 'Eson', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
